name: Provision AWS and Deploy to VPS

on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read

jobs:
  provision:
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/provision.yml
    secrets: inherit

  deploy_app:
    needs: provision
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/deploy-app.yml
    with:
      queue_url: ${{ needs.provision.outputs.queue_url }}
      app_runtime_aws_access_key_id: ${{ needs.provision.outputs.app_runtime_aws_access_key_id }}
      app_runtime_aws_secret_access_key: ${{ needs.provision.outputs.app_runtime_aws_secret_access_key }}
    secrets: inherit
